"""
Sandboxed ComfyUI Runtime Process Supervisor.

Manages isolated execution of the local ComfyUI engine in a dedicated,
hermetic application directory (~/.ai-workflow/engine or %LOCALAPPDATA%/AI-Workflow/engine).
Guarantees zero system environment pollution and strictly disallows host Python fallback.
"""

import os
import signal
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional
from app.runtime.process_diagnostics import ProcessDiagnostics



def get_default_engine_dir() -> Path:
    """Return the root isolated engine directory, configurable via env var."""
    custom_dir = os.environ.get("AI_WORKFLOW_ENGINE_DIR")
    if custom_dir:
        return Path(custom_dir).resolve()

    if sys.platform == "win32":
        local_app_data = os.environ.get("LOCALAPPDATA", str(Path.home() / "AppData" / "Local"))
        return Path(local_app_data) / "AI-Workflow" / "engine"

    return Path.home() / ".ai-workflow" / "engine"


class ComfySupervisor:
    """Supervisor managing the lifecycle of an isolated ComfyUI subprocess."""

    def __init__(
        self,
        engine_dir: Optional[Path] = None,
        port: int = 8188,
        extra_args: Optional[List[str]] = None,
    ) -> None:
        self.engine_dir = engine_dir or get_default_engine_dir()
        self.port = port
        self.extra_args: List[str] = list(extra_args) if extra_args else []
        self.runtime_dir = self.engine_dir / "runtime"
        self.comfy_dir = self.engine_dir / "comfyui"
        self.models_dir = self.engine_dir / "models"
        self.pid_file = self.engine_dir / "comfy.pid"
        self._process: Optional[subprocess.Popen] = None
        self.diagnostics = ProcessDiagnostics(self.engine_dir / "logs" / "comfyui.log")

    def ensure_directories(self) -> None:
        """Ensure the isolated engine directory layout exists."""
        self.engine_dir.mkdir(parents=True, exist_ok=True)
        self.models_dir.mkdir(parents=True, exist_ok=True)
        (self.models_dir / "checkpoints").mkdir(exist_ok=True)
        (self.models_dir / "loras").mkdir(exist_ok=True)
        (self.models_dir / "vae").mkdir(exist_ok=True)

    def is_installed(self) -> bool:
        """Check if the isolated ComfyUI installation exists and has entrypoint."""
        main_py = self.comfy_dir / "main.py"
        return main_py.is_file()

    def get_python_bin(self) -> Path:
        """Return the expected path to the isolated virtualenv python binary."""
        if sys.platform == "win32":
            return self.runtime_dir / "Scripts" / "python.exe"
        return self.runtime_dir / "bin" / "python"

    def has_isolated_env(self) -> bool:
        """Check if the sandboxed isolated virtual environment is ready."""
        return self.get_python_bin().is_file()

    def _generate_extra_model_paths_config(self) -> Path:
        """Generate extra_model_paths.yaml to connect shared model directories to ComfyUI search paths."""
        config_path = self.engine_dir / "extra_model_paths.yaml"
        config_content = f"""# ComfyUI Extra Model Paths Configuration
# Generated by Berry AI Studio to connect downloaded models to ComfyUI engine search paths.

berry_shared:
    base_path: {self.models_dir}

    checkpoints: checkpoints/
    vae: vae/
    loras: loras/
    upscale_models: upscale_models/
    controlnet: controlnet/
"""
        config_path.write_text(config_content, encoding="utf-8")
        return config_path

    def _is_owned_executable(self, exe_path: Path) -> bool:
        """Ensure the executable strictly resides in the isolated virtualenv or engine directory."""
        try:
            exe_res = exe_path.resolve()
            expected_bin = self.get_python_bin().resolve()
            if exe_res == expected_bin:
                return True
            runtime_res = self.runtime_dir.resolve()
            if runtime_res in exe_res.parents:
                return True
            engine_res = self.engine_dir.resolve()
            if engine_res in exe_res.parents:
                return True
            comfy_res = self.comfy_dir.resolve()
            if comfy_res in exe_res.parents:
                return True
        except Exception:
            pass
        return False

    def _verify_process_identity(self, pid: int) -> bool:
        """Verify the process at pid is actually owned by this supervisor, avoiding recycled PID collision."""
        if sys.platform == "win32":
            try:
                import ctypes
                from ctypes import wintypes
                kernel32 = ctypes.windll.kernel32
                handle = kernel32.OpenProcess(0x1000, False, pid)  # PROCESS_QUERY_LIMITED_INFORMATION
                if not handle:
                    return False
                try:
                    buf = ctypes.create_unicode_buffer(1024)
                    size = wintypes.DWORD(1024)
                    success = kernel32.QueryFullProcessImageNameW(handle, 0, buf, ctypes.byref(size))
                    if success:
                        exe_path = Path(buf.value)
                        return self._is_owned_executable(exe_path)
                    return False
                finally:
                    kernel32.CloseHandle(handle)
            except Exception:
                return False
        else:
            try:
                proc_exe = Path(f"/proc/{pid}/exe")
                if proc_exe.exists():
                    resolved = Path(os.readlink(proc_exe))
                    if self._is_owned_executable(resolved):
                        return True
                proc_cmdline = Path(f"/proc/{pid}/cmdline")
                if proc_cmdline.is_file():
                    content = proc_cmdline.read_text(encoding="latin1", errors="ignore")
                    if str(self.comfy_dir) in content or str(self.runtime_dir) in content:
                        return True
                return False
            except (OSError, Exception):
                return False

    def get_pid(self) -> Optional[int]:
        """Read active PID from the supervisor PID file if process is alive and verified."""
        if not self.pid_file.is_file():
            return None

        try:
            pid = int(self.pid_file.read_text(encoding="utf-8").strip())
            if self._verify_process_identity(pid):
                return pid
        except (ValueError, OSError):
            pass

        # Cleanup stale pid file
        self._clean_pid_file()
        return None

    def is_running(self) -> bool:
        """Check if the managed ComfyUI process is actively running."""
        return self.get_pid() is not None

    def get_status(self) -> Dict[str, Any]:
        """Return comprehensive status of the isolated runtime."""
        pid = self.get_pid()
        return {
            "installed": self.is_installed(),
            "isolated_env_ready": self.has_isolated_env(),
            "running": pid is not None,
            "pid": pid,
            "port": self.port,
            "extra_args": list(self.extra_args),
            "engine_dir": str(self.engine_dir),
            "runtime_dir": str(self.runtime_dir),
            "comfy_dir": str(self.comfy_dir),
            "models_dir": str(self.models_dir),
        }

    def start(self) -> Dict[str, Any]:
        """Launch the isolated ComfyUI process strictly inside its hermetic environment."""
        if not self.is_installed():
            return {
                "success": False,
                "code": "NOT_INSTALLED",
                "message": f"ComfyUI is not installed in {self.comfy_dir}. Run installer first.",
            }

        python_bin = self.get_python_bin()
        if not python_bin.is_file():
            # STRICT REQUIREMENT: Zero host Python fallback!
            return {
                "success": False,
                "code": "ENV_MISSING",
                "message": (
                    f"Sandboxed virtual environment not found at {python_bin}. "
                    "Run the isolated installer to set up the engine runtime without host pollution."
                ),
            }

        if self.is_running():
            return {
                "success": True,
                "message": f"ComfyUI is already running (PID: {self.get_pid()})",
                "pid": self.get_pid(),
            }

        from app.runtime.hardware import get_hardware_launch_flags
        hw_flags = get_hardware_launch_flags()

        # Generate extra model paths config for shared model directories
        extra_paths_config = self._generate_extra_model_paths_config()

        cmd = [
            str(python_bin),
            str(self.comfy_dir / "main.py"),
            "--port",
            str(self.port),
            "--listen",
            "127.0.0.1",
            "--input-directory",
            str(self.engine_dir / "input"),
            "--output-directory",
            str(self.engine_dir / "output"),
            "--extra-model-paths-config",
            str(extra_paths_config),
            *hw_flags,
        ]

        # Append configured extra launch arguments (avoid exact duplicates)
        for arg in self.extra_args:
            if arg not in cmd:
                cmd.append(arg)

        try:
            self.ensure_directories()
            self._process = subprocess.Popen(
                cmd,
                cwd=str(self.comfy_dir),
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                creationflags=subprocess.CREATE_NO_WINDOW if sys.platform == "win32" else 0,
            )
            self.diagnostics.attach(self._process)
            pid = self._process.pid
            self.pid_file.write_text(str(pid), encoding="utf-8")
            return {
                "success": True,
                "message": f"ComfyUI launched successfully (PID: {pid})",
                "pid": pid,
            }
        except Exception as err:
            return {
                "success": False,
                "message": f"Failed to launch ComfyUI: {err}",
            }

    def get_recent_logs(self, lines: int = 100) -> List[str]:
        return self.diagnostics.recent(lines)

    def stop(self) -> Dict[str, Any]:
        """Terminate the managed ComfyUI process with process identity verification."""
        pid = self.get_pid()
        if pid is None:
            return {"success": True, "message": "ComfyUI is not running"}

        if not self._verify_process_identity(pid):
            self._clean_pid_file()
            return {
                "success": False,
                "message": f"Process {pid} is not a verified ComfyUI process; refusing to kill.",
            }

        try:
            if sys.platform == "win32":
                subprocess.run(["taskkill", "/F", "/T", "/PID", str(pid)], capture_output=True, check=False)
            else:
                os.kill(pid, signal.SIGTERM)
        except Exception as err:
            return {"success": False, "message": f"Error stopping process: {err}"}
        finally:
            self._clean_pid_file()

        return {"success": True, "message": f"ComfyUI process {pid} stopped"}

    def _clean_pid_file(self) -> None:
        try:
            if self.pid_file.is_file():
                self.pid_file.unlink()
        except OSError:
            pass


# Global default supervisor singleton
supervisor = ComfySupervisor()
